# Generated by Django 4.2.4 on 2023-08-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_carousel_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='research_area')),
            ],
            options={
                'verbose_name_plural': 'research areas',
            },
        ),
    ]
