# Generated by Django 4.2.4 on 2023-08-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_researcharea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carousel',
        ),
    ]
