# Generated by Django 4.2.4 on 2023-08-04 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_delete_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='research_details')),
            ],
            options={
                'verbose_name_plural': 'research details',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='research')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.category')),
                ('research_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.researcharea')),
            ],
            options={
                'verbose_name_plural': 'researches',
            },
        ),
        migrations.CreateModel(
            name='RepresentativePublications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('authers', models.TextField()),
                ('doi', models.CharField(max_length=100)),
                ('journal', models.CharField(max_length=100)),
                ('publish_year', models.CharField(max_length=100)),
                ('publish_issue', models.CharField(max_length=100)),
                ('publish_page', models.CharField(max_length=100)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.researchdetails')),
            ],
            options={
                'verbose_name_plural': 'representatives',
            },
        ),
    ]
