# Generated by Django 4.2.4 on 2023-08-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_researchdetails_research_representativepublications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='representativepublications',
            options={'verbose_name_plural': 'representative publications'},
        ),
        migrations.RemoveField(
            model_name='representativepublications',
            name='research',
        ),
        migrations.AddField(
            model_name='researchdetails',
            name='publications',
            field=models.ManyToManyField(to='website.representativepublications'),
        ),
        migrations.AlterField(
            model_name='representativepublications',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Research',
        ),
    ]
