# Generated by Django 4.2.4 on 2023-08-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_representativepublications_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='representativepublications',
            old_name='authers',
            new_name='authors',
        ),
    ]
